version: '2'
services:

  ingress:
    extends:
      file: ./ingress/ingress.yml
      service: ingress
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`localhost`)'
      - 'traefik.http.routers.api.entrypoints=https'
      - 'traefik.http.routers.api.service=api@internal'
      - 'traefik.http.routers.api.tls=true'
      - 'traefik.http.routers.api.tls.options=default'

  sso:
    extends:
      file: ./sso/sso.yml
      service: sso
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`localhost`) && PathPrefix(`/sso`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.routers.authelia.tls.options=default'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://sso:9091/api/verify?rd=https%3A%2F%2Flocalhost%2Fsso%2F'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
      - "traefik.http.routers.sso.middlewares=sso-strip-prefix@docker"
      - "traefik.http.middlewares.sso-strip-prefix.stripprefix.prefixes=/sso"

  # Test containers
  whoami1:
    image: containous/whoami
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami1.entrypoints=https'
      - 'traefik.http.routers.whoami1.tls=true'
      - 'traefik.http.routers.whoami1.tls.options=default'
      - "traefik.http.routers.whoami1.rule=Host(`localhost`) && Path(`/whoami1`)"
      - "traefik.http.routers.whoami1.middlewares=authelia@docker,whoami1-strip-prefix@docker,whoami1-testheader@docker"
      - "traefik.http.middlewares.whoami1-strip-prefix.stripprefix.prefixes=/whoami1"
      - "traefik.http.middlewares.whoami1-testheader.headers.customrequestheaders.X-Service-Name=whoami1"
  whoami2:
    image: containous/whoami
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.whoami2.entrypoints=https'
      - 'traefik.http.routers.whoami2.tls=true'
      - 'traefik.http.routers.whoami2.tls.options=default'
      - "traefik.http.routers.whoami2.rule=Host(`localhost`) && Path(`/whoami2`)"
      - "traefik.http.routers.whoami2.middlewares=authelia@docker,whoami2-strip-prefix@docker,whoami2-testheader@docker"
      - "traefik.http.middlewares.whoami2-strip-prefix.stripprefix.prefixes=/whoami2"
      - "traefik.http.middlewares.whoami2-testheader.headers.customrequestheaders.X-Service-Name=whoami2"
